%ifndef THEMES_INC
%define THEMES_INC

%include "raylib.inc"
%include "std.inc"

; Color theme_gray_scale(double, bool);
extern theme_gray_scale

; Color theme_hue_full(double, bool);
extern theme_hue_full

; Color theme_hue_red(double, bool);
extern theme_hue_red

; Color theme_hue_green(double, bool);
extern theme_hue_green

; Color theme_hue_blue(double, bool);
extern theme_hue_blue

%endif ; THEMES_INC
